In [1]:

import numpy as np 
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv('/Users/macbookair/Desktop/Machine Learning/Feature_Scaling/Column Transformer/covid_toy.csv')

In [3]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [6]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    object 
 2   fever      90 non-null     float64
 3   cough      100 non-null    object 
 4   city       100 non-null    object 
 5   has_covid  100 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB


# train test split


In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns = ['has_covid']),df['has_covid'],test_size = 0.2)

In [6]:
X_train

age  gender  fever   cough       city
69   73  Female  103.0    Mild      Delhi
68   54  Female  104.0  Strong    Kolkata
52   47  Female  100.0  Strong  Bangalore
19   42  Female    NaN  Strong  Bangalore
62   56  Female  104.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
23   80  Female   98.0    Mild      Delhi
76   80    Male  100.0    Mild  Bangalore
73   34    Male   98.0  Strong    Kolkata
84   69  Female   98.0  Strong     Mumbai
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [10]:
X_test

age  gender  fever   cough       city
36   38  Female  101.0    Mild  Bangalore
6    14    Male  101.0  Strong  Bangalore
22   71  Female   98.0  Strong    Kolkata
53   83    Male   98.0    Mild      Delhi
96   51  Female  101.0  Strong    Kolkata
28   16    Male  104.0    Mild    Kolkata
39   50  Female  103.0    Mild    Kolkata
38   49  Female  101.0    Mild      Delhi
87   47    Male  101.0  Strong  Bangalore
70   68  Female  101.0  Strong      Delhi
67   65    Male   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
49   44    Male  104.0    Mild     Mumbai
76   80    Male  100.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi
92   82  Female  102.0  Strong    Kolkata
42   27    Male  100.0    Mild      Delhi
7    20  Female    NaN  Strong     Mumbai
85   16  Female  103.0    Mild  Bangalore
26   19  Female  100.0    Mild    Kolkata

# Without column transformer


In [7]:
# adding simpler imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

#also the test data
X_test_fever = si.fit_transform(X_test[['fever']])


In [8]:
X_test_fever

array([[101.    ],
       [ 98.    ],
       [103.    ],
       [103.    ],
       [101.    ],
       [101.1875],
       [101.1875],
       [101.1875],
       [101.1875],
       [103.    ],
       [ 98.    ],
       [100.    ],
       [101.    ],
       [ 98.    ],
       [102.    ],
       [103.    ],
       [101.    ],
       [104.    ],
       [ 99.    ],
       [104.    ]])

In [16]:
X_train_fever

array([[103.        ],
       [104.        ],
       [100.        ],
       [100.77027027],
       [104.        ],
       [100.77027027],
       [ 98.        ],
       [101.        ],
       [102.        ],
       [ 99.        ],
       [102.        ],
       [101.        ],
       [104.        ],
       [104.        ],
       [103.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [100.77027027],
       [102.        ],
       [101.        ],
       [100.        ],
       [ 98.        ],
       [102.        ],
       [103.        ],
       [102.        ],
       [101.        ],
       [102.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [100.77027027],
       [100.77027027],
       [101.        ],
       [ 98.        ],
       [100.        ],
       [104.        ],
       [102.        ],
       [ 98.        ],
       [103.        ],
       [ 99

In [17]:
#OrdinalEncoding->cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.fit_transform(X_train[['cough']])



In [18]:
X_train_cough

array([[0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],

In [19]:
#OneHotEncoding->gender,city

ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = ohe.fit_transform(X_train[['gender','city']])


In [20]:
X_train_age = X_train.drop(columns = ['gender','fever','cough','city']).values
X_test_age = X_test.drop(columns = ['gender','fever','cough','city']).values

In [21]:
X_train_concatenate = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
X_test_concatenate = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)

In [25]:
X_train_concatenate.shape

(80, 7)

In [26]:
X_train_concatenate

array([[ 73.        , 103.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 19.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 10.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 70.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 47.        , 100.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 55.        , 100.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 15.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 12.        ,  98.        ,   1.        ,   0.        ,
          0.    

# With Column Transformer

In [14]:
from sklearn.compose import     ColumnTransformer




In [28]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2' , OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3', OneHotEncoder(sparse_output=  False,drop='first'),['gender','city'])]
    ,remainder='passthrough')

In [29]:
transformer.fit_transform(X_train)

array([[103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  73.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  54.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [100.77027027,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [100.77027027,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  38.        ],
       [ 98.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  19.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          1.    

In [30]:
transformer.fit_transform(X_test)

array([[101.    ,   0.    ,   0.    ,   0.    ,   1.    ,   0.    ,
         83.    ],
       [ 98.    ,   0.    ,   0.    ,   0.    ,   1.    ,   0.    ,
         26.    ],
       [103.    ,   0.    ,   0.    ,   0.    ,   0.    ,   0.    ,
         16.    ],
       [103.    ,   0.    ,   1.    ,   0.    ,   1.    ,   0.    ,
         60.    ],
       [101.    ,   0.    ,   0.    ,   0.    ,   0.    ,   1.    ,
         81.    ],
       [101.1875,   0.    ,   1.    ,   0.    ,   1.    ,   0.    ,
         82.    ],
       [101.1875,   1.    ,   1.    ,   0.    ,   1.    ,   0.    ,
         71.    ],
       [101.1875,   1.    ,   0.    ,   0.    ,   0.    ,   1.    ,
         34.    ],
       [101.1875,   0.    ,   1.    ,   0.    ,   0.    ,   1.    ,
         23.    ],
       [103.    ,   0.    ,   1.    ,   0.    ,   1.    ,   0.    ,
         83.    ],
       [ 98.    ,   0.    ,   0.    ,   0.    ,   0.    ,   0.    ,
         64.    ],
       [100.    ,   0.    ,   0.    ,   0. 