In [1]:
import numpy as np
import pandas as pd

np.random.seed(23) # random numbers generated are the same every time you run this code

mu_vec1 = np.array([0,0,0]) # mean vector for the first class
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)  # 20*3 array of samples from the first class

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])
df1['target'] = 0


df = pd.concat([df, df1], ignore_index=True)



In [2]:
df = df.sample(40)

In [3]:
df.head()

,feature1,feature2,feature3,target
2,-0.367548,-1.137460,-1.322148,1
34,0.177061,-0.598109,1.226512,0
14,0.420623,0.411620,-0.071324,1
11,1.968435,-0.547788,-0.679418,1
12,-2.506230,0.146960,0.606195,1


In [11]:
import sys
!{sys.executable} -m pip install plotly


  Using cached plotly-6.5.2-py3-none-any.whl.metadata (8.5 kB)
  Using cached narwhals-2.16.0-py3-none-any.whl.metadata (14 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 6.1 MB/s  0:00:01 eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [plotly]2m1/2 [plotly]


In [19]:
import plotly.express as px

fig = px.scatter_3d(df.astype({'target':str}), x='feature1', y='feature2', z='feature3', color='target')

fig.update_traces(marker = dict(size=12,line = dict(width=2,color='DarkSlateGrey')), selector=dict(mode='markers'))
# fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'target=1<br>feature1=%{x}<br>feature2=%{y}<br>feature3=%{z}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#636efa',
                         'line': {'color': 'DarkSlateGrey', 'width': 2},
                         'size': 12,
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': '1',
              'scene': 'scene',
              'showlegend': True,
              'type': 'scatter3d',
              'x': {'bdata': ('xU1OzgZt5r9MExPafnaHv/moHjELev' ... 'Uhitm/oD08nyVU5z8IeNEGQLvyPw=='),
                    'dtype': 'f8'},
              'y': {'bdata': ('V33WGc1o+L+CltKRzQeov0DG8nyhzu' ... '9uVNu/On5JnN2K0b/+FymGJbDovw=='),
                    'dtype': 'f8'},
              'z': {'bdata': ('uh3sUIv8+7+lzj+Bpsnkv3g0EtlU8v' ... '2ZL84/hHVTf3iY+r9hCtYY9chhPw=='),
                    'dtype': 'f8'}},
             {'hovertemplate': 'target=0<br>feature1=%{x}<br>feature2=%{y}<br>feature3=%{z}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#EF553B',
                         'line': {'color': 'DarkSlateGrey', 'width': 2},
                         'size': 12,
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': '0',
              'scene': 'scene',
              'showlegend': True,
              'type': 'scatter3d',
              'x': {'bdata': ('UiFCC8q7zL/jZIyzbb/rPyjsGFcjD/' ... 'R8pcm/lhBGFs+j0T/elHsPMmXmPw=='),
                    'dtype': 'f8'},
              'y': {'bdata': ('W7TETQ8s8L/3TDTr/vHtP1QkLIcmJs' ... '6+2ty/uJJXmHNIAEAVpBus8uzYvw=='),
                    'dtype': 'f8'},
              'z': {'bdata': ('2jpwjKlw3z/b1mAawErbv15Y+GxVgd' ... 'dYdgFAJIikr4hO3D+bYiU8siPqvw=='),
                    'dtype': 'f8'}}],
    'layout': {'legend': {'title': {'text': 'target'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'scene': {'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
                         'xaxis': {'title': {'text': 'feature1'}},
                         'yaxis': {'title': {'text': 'feature2'}},
                         'zaxis': {'title': {'text': 'feature3'}}},
               'template': '...'}
})

In [15]:
# step-1 : Apply standard scaling 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])



In [16]:
# step-2: Find covariance matrix of the features
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)



Covariance Matrix:
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [20]:
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [21]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [22]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [26]:
%pylab inline

from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d import proj3d
from matplotlib.patches import FancyArrowPatch


class Arrow3D(FancyArrowPatch):
    def __init__(self, xs, ys, zs, *args, **kwargs):
        FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)
        self._verts3d = xs, ys, zs

    def draw(self, renderer):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
        self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))
        FancyArrowPatch.draw(self, renderer)

fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')

ax.plot(df['feature1'], df['feature2'], df['feature3'], 'o', markersize=8, color='blue', alpha=0.2)
ax.plot([df['feature1'].mean()], [df['feature2'].mean()], [df['feature3'].mean()], 'o', markersize=10, color='red', alpha=0.5)
for v in eigen_vectors.T:
    a = Arrow3D([df['feature1'].mean(), v[0]], [df['feature2'].mean(), v[1]], [df['feature3'].mean(), v[2]], mutation_scale=20, lw=3, arrowstyle="-|>", color="r")
    ax.add_artist(a)
ax.set_xlabel('x_values')
ax.set_ylabel('y_values')
ax.set_zlabel('z_values')

plt.title('Eigenvectors')


     

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


Text(0.5, 0.92, 'Eigenvectors')

Error in callback <function _draw_all_if_interactive at 0x289089f80> (for post_execute), with arguments args (),kwargs {}:


AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'

AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'

<Figure size 700x700 with 1 Axes>